name: MeraDoctor
favicon: null
layout_spectrum: 0.22568972152657807
typography_spectrum: 0.9617773997597396
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6091753020882607
  lightness: 0.4740119534544647
  saturation: 0.5540064217057079
  rhythmicContrast: 0.38978157145902514
purpose: []
